[build]
builder = "DOCKERFILE"
dockerfilePath = "bookstore/Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
