ALTER TABLE users ADD COLUMN IF NOT EXISTS lifetime_points BIGINT NOT NULL DEFAULT 0 CHECK (lifetime_points >= 0);

ALTER TABLE vouchers ADD COLUMN IF NOT EXISTS used_count INT NOT NULL DEFAULT 0 CHECK (used_count >= 0);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_transaction_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE voucher_redemptions ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING','ACTIVE'));

ALTER TABLE conversations ADD COLUMN IF NOT EXISTS title VARCHAR(255);
